// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUoGGAhxt0N6mqmD5seD4PLWCcBWkj8cY',
    appId: '1:917039863920:web:94fb7669f55d027b223cb5',
    messagingSenderId: '917039863920',
    projectId: 'study-informatika-6d21b',
    authDomain: 'study-informatika-6d21b.firebaseapp.com',
    databaseURL: 'https://study-informatika-6d21b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'study-informatika-6d21b.appspot.com',
    measurementId: 'G-D0BH0HZ6GZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOdAfo26phtRBhpUD10L5PrqCVELItbX4',
    appId: '1:917039863920:android:345c682bffc9dff0223cb5',
    messagingSenderId: '917039863920',
    projectId: 'study-informatika-6d21b',
    databaseURL: 'https://study-informatika-6d21b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'study-informatika-6d21b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiF4BrhjrV36UEtUZZz4HJpsNY4hgfg2Y',
    appId: '1:917039863920:ios:2c307bc5e014af84223cb5',
    messagingSenderId: '917039863920',
    projectId: 'study-informatika-6d21b',
    databaseURL: 'https://study-informatika-6d21b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'study-informatika-6d21b.appspot.com',
    iosClientId: '917039863920-h9ukbgagtt9isd04q8uo0aarhk3j6elp.apps.googleusercontent.com',
    iosBundleId: 'com.example.quiz3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiF4BrhjrV36UEtUZZz4HJpsNY4hgfg2Y',
    appId: '1:917039863920:ios:b23629ba3d1c3588223cb5',
    messagingSenderId: '917039863920',
    projectId: 'study-informatika-6d21b',
    databaseURL: 'https://study-informatika-6d21b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'study-informatika-6d21b.appspot.com',
    iosClientId: '917039863920-r1ojj9jujrqame60ongc3jsf0efro85c.apps.googleusercontent.com',
    iosBundleId: 'com.example.quiz3.RunnerTests',
  );
}
